/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.telas;

import br.contasreceber.ContasReceber;
import br.contasreceber.ContasReceberDAO;
import br.contasreceber.ContasReceberTableModel;
import br.util.HibernateUtil;
import br.util.Util;
import br.venda.Venda;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaFechaVendaPromissoria extends javax.swing.JDialog {

    private static Venda venda;

    public static void chamaTela(Venda venda) {
        TelaFechaVendaPromissoria.venda = venda;
        new TelaFechaVendaPromissoria().setVisible(true);
    }

    /**
     * Creates new form TelaFechaVendaPromissoria
     */
    public TelaFechaVendaPromissoria() {
        initComponents();
        setTitle("Fecha Venda Promissória");
        setModal(true);
        setLocationRelativeTo(null);
        tfQtParcelas.setText("1");
        tfQtdDias.setText("30");
        preencheTabela();
        lblValor.setText("Valor Promissória: " + String.valueOf(venda.getVlPromissoria()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        btImprimir = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tfQtdDias = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfQtParcelas = new javax.swing.JFormattedTextField();
        btGerar = new javax.swing.JButton();
        lblValor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 550, 150));

        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/print.png"))); // NOI18N
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 50, -1));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/cancel.png"))); // NOI18N
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel1.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 50, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tfQtdDias.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        tfQtdDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfQtdDiasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Qtd Dias.: *");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Qtd Parcelas.: *");

        tfQtParcelas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        btGerar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btGerar.setText("Gerar");
        btGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(tfQtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btGerar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(tfQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(tfQtdDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfQtParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGerar))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 80));

        lblValor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lblValor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblValor.setText("jLabel3");
        jPanel1.add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 350, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfQtdDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQtdDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQtdDiasActionPerformed

    private void btGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerarActionPerformed
        // TODO add your handling code here:
        if (!tfQtParcelas.getText().equals("") && !tfQtdDias.getText().equals("")) {
            int qtdParcelas = Integer.parseInt(tfQtParcelas.getText());
            int qtdDias = Integer.parseInt(tfQtdDias.getText());
            Date dataVencimento = new Date();

            Date dt = new Date();
            SimpleDateFormat dfdtDataNascimento;
            SimpleDateFormat data = new SimpleDateFormat("ddMMyy");
            SimpleDateFormat hora = new SimpleDateFormat("hhmm");
            DecimalFormat df = new DecimalFormat("#.00");

            for (int i = 0; i < qtdParcelas; i++) {
                ContasReceber cr = new ContasReceber();
                ContasReceberDAO crDAO = new ContasReceberDAO();

                cr.setVenda(venda);
                cr.setCliente(venda.getCliente());
                cr.setPaga(false);
//                cr.setNrConta(Util.decimalFormat().format(cr.getCliente().getId()+cr.getId()));

                Calendar c = Calendar.getInstance();
                c.setTime(dataVencimento);
                c.add(Calendar.DATE, qtdDias);

                dataVencimento = c.getTime();
                cr.setDataVencimento(dataVencimento);
                double valor = venda.getVlPromissoria() / qtdParcelas;
                cr.setValor(Double.valueOf(df.format(valor).replace(",", ".")));
                cr.setNrParcela(i + 1);

                cr.setNrConta(cr.getCliente().getId() + data.format(dt) + hora.format(dt) + "-" + cr.getNrParcela());

                crDAO.add(cr);

            }

            tfQtParcelas.setEnabled(false);
            tfQtdDias.setEnabled(false);
            btGerar.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe os Campos Obrigatórios (*)!");
        }
        preencheTabela();
    }//GEN-LAST:event_btGerarActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        JasperReport pathjrxml;
        HashMap parametros = new HashMap();

        String sql = String.valueOf(venda.getId());

        try {
            parametros.put("sql", sql);
        } catch (Exception e) {
        }

        String caminho = Util.retornaCaminhoApp();
//        String caminho = "";

        Connection connection = HibernateUtil.getSessionFactory().openStatelessSession().connection();
        try {
            JDialog viewer = new JDialog(new javax.swing.JFrame(), "Visualização do Relatório", true);
            viewer.setSize(1200, 600);
            viewer.setLocationRelativeTo(null);
            viewer.setModal(true);
            File file = new File(caminho + "relatorios/reportPromissorias.jrxml");
            FileInputStream is = new FileInputStream(file);
            pathjrxml = JasperCompileManager.compileReport(is);
            JasperPrint printReport = JasperFillManager.fillReport(pathjrxml, parametros,
                    connection);
            JasperViewer jv = new JasperViewer(printReport, false);
            viewer.getContentPane().add(jv.getContentPane());
            viewer.setVisible(true);
                //JasperExportManager.exportReportToPdfFile(printReport, "src/relatorios/RelAcervo.pdf");

            //jv.setVisible(true);
        } catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        // TODO add your handling code here:
        ContasReceberDAO crDAO = new ContasReceberDAO();
        List<ContasReceber> lista = crDAO.checkExists("venda", venda);
        if(lista.size()>0){
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Gere as parcelas!");
        }
        
    }//GEN-LAST:event_btSairActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        ContasReceberDAO crDAO = new ContasReceberDAO();
        List<ContasReceber> lista = crDAO.checkExists("venda", venda);
        if(lista.size()>0){
            
        } else {
            repaint();
            JOptionPane.showMessageDialog(rootPane, "Gere as parcelas!");
        }
    }//GEN-LAST:event_formWindowClosing

    private void preencheTabela() {
        ContasReceberDAO crDAO = new ContasReceberDAO();
        List<ContasReceber> lista = crDAO.checkExists("venda", venda);
        ContasReceberTableModel crtm = new ContasReceberTableModel(lista);
        tb.setModel(crtm);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFechaVendaPromissoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFechaVendaPromissoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFechaVendaPromissoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFechaVendaPromissoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFechaVendaPromissoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGerar;
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tb;
    private javax.swing.JFormattedTextField tfQtParcelas;
    private javax.swing.JFormattedTextField tfQtdDias;
    // End of variables declaration//GEN-END:variables
}
