/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.telas;

import br.cliente.Cliente;
import br.cliente.ClienteDAO;
import br.contasreceber.ContasReceber;
import br.contasreceber.ContasReceberDAO;
import br.empresa.Empresa;
import br.empresa.EmpresaDAO;
import br.livro.LivroCaixa;
import br.livro.LivroCaixaDAO;
import br.orcamento.ItemOrcamento;
import br.orcamento.ItemOrcamentoDAO;
import br.orcamento.ItemOrcamentoTableModel;
import br.orcamento.Orcamento;
import br.orcamento.OrcamentoDAO;
import br.produto.Estoque;
import br.produto.EstoqueDAO;
import br.produto.ProdutoTableModel;
import br.produto.Produto;
import br.produto.ProdutoDAO;
import br.util.FormataTamanhoColunasJTable;
import br.util.UsuarioAtivo;
import br.util.Util;
import br.venda.ItemVenda;
import br.venda.ItemVendaCellRenderer;
import br.venda.ItemVendaDAO;
import br.venda.ItemVendaTableModel;
import br.venda.Venda;
import br.venda.VendaDAO;
import br.vendedor.Vendedor;
import br.vendedor.VendedorDAO;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaOrcamento extends javax.swing.JDialog {

    private List<ItemOrcamento> itensOrcamento;
    private Produto produto;
    private Orcamento orcamento = new Orcamento();

    private void preencheEmpresa(){
        EmpresaDAO eDAO = new EmpresaDAO();
        List<Empresa> eList = eDAO.list();
        if(eList.size()>0){
            Empresa e = eList.get(0);
            lblCidade.setText(e.getCidade()+"-"+e.getEstado());
            lblRazaoSocial.setText(e.getRazaoSocial());
            lblRua.setText(e.getEndereco());
            lblTelefone.setText(e.getTelefone());
        } else {
            lblCidade.setText("");
            lblRazaoSocial.setText("");
            lblRua.setText("");
            lblTelefone.setText("");
        }
    }
    /**
     * Creates new form TelaVenda
     */
    public TelaOrcamento() {
        initComponents();
        setTitle("Orçamento");
        setLocationRelativeTo(null);
        setModal(true);
        preencheEmpresa();
        limpaCampos();

    }

    public void preencheVendedor() {
        cbVendedor.removeAllItems();
        cbVendedor.addItem("--");
        VendedorDAO vDAO = new VendedorDAO();
        List<Vendedor> lista = vDAO.checkExists("ativo", true);
        Collections.sort(lista);
        for (Vendedor v : lista) {
            cbVendedor.addItem(v);
        }
    }

    public void preencheCliente() {
        cbCliente.removeAllItems();
        cbCliente.addItem("--");
        ClienteDAO cDAO = new ClienteDAO();
        List<Cliente> lista = cDAO.checkExists("ativo", true);
        Collections.sort(lista);
        for (Cliente c : lista) {
            cbCliente.addItem(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbTexto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbTipoPagamento = new javax.swing.JComboBox();
        cbVendedor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDataVencimento = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblDescricaoProduto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalFinal = new javax.swing.JLabel();
        lblDesconto1 = new javax.swing.JLabel();
        lblParcial = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblRazaoSocial = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblRua = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTexto.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 1, 36)); // NOI18N
        lbTexto.setForeground(new java.awt.Color(255, 255, 255));
        lbTexto.setText("ORÇAMENTO");
        jPanel4.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 40));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 659, 201));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel2.setText("Tipo Pagamento.: *");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        cbTipoPagamento.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        cbTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Venda à Vista", "Venda à Prazo", "Venda à Cartão" }));
        cbTipoPagamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbTipoPagamentoFocusLost(evt);
            }
        });
        jPanel2.add(cbTipoPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 13, 182, -1));

        cbVendedor.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        cbVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Venda à Vista", "Venda à Prazo", "Venda à Cartão" }));
        jPanel2.add(cbVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 41, 182, -1));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel3.setText("Vendedor.: *");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 44, -1, -1));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel1.setText("Cliente.: *");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 72, -1, -1));

        cbCliente.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        cbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        cbCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbClienteFocusLost(evt);
            }
        });
        jPanel2.add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 69, 386, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel4.setText("Data.: *");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 16, -1, -1));

        lblData.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblData.setText("Data.: *");
        jPanel2.add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 125, 20));

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel7.setText("Validade.: *");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        lblDataVencimento.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblDataVencimento.setText("Data.: *");
        jPanel2.add(lblDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 125, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 100));
        jPanel2.getAccessibleContext().setAccessibleParent(jPanel2);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/codbarras.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, 55));

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel5.setText("Quantidade.: *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        lblDescricaoProduto.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblDescricaoProduto.setText(" ");
        jPanel1.add(lblDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 260, 20));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel6.setText("Descrição.: *");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 121, -1, 20));

        tfQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfQuantidade.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 14)); // NOI18N
        tfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfQuantidadeKeyPressed(evt);
            }
        });
        jPanel1.add(tfQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/add.png"))); // NOI18N
        jButton2.setToolTipText("Adicionar Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 50, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/delete (1).png"))); // NOI18N
        jButton3.setToolTipText("Cancelar Produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 140, 50, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/pataverde.png"))); // NOI18N
        jButton4.setToolTipText("Finalizar Orçamento");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 50, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/delete.png"))); // NOI18N
        jButton5.setToolTipText("Cancelar Orçamento");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 50, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel9.setText("Desc.:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel8.setText("Total:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        lblTotalFinal.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblTotalFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(lblTotalFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 90, 20));

        lblDesconto1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblDesconto1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(lblDesconto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 20));

        lblParcial.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblParcial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel3.add(lblParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 90, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 160, 80));

        lblCidade.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCidade.setText("ORÇAMENTO NÃO E VÁLIDO COMO GARANTIA DE MERCADORIA");
        jPanel1.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 490, -1));

        jLabel11.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("ORÇAMENTO NÃO E VÁLIDO COMO GARANTIA DE MERCADORIA");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, 560, -1));

        lblRazaoSocial.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblRazaoSocial.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRazaoSocial.setText("ORÇAMENTO NÃO E VÁLIDO COMO GARANTIA DE MERCADORIA");
        jPanel1.add(lblRazaoSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 490, -1));

        lblTelefone.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTelefone.setText("ORÇAMENTO NÃO E VÁLIDO COMO GARANTIA DE MERCADORIA");
        jPanel1.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 490, -1));

        lblRua.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblRua.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRua.setText("ORÇAMENTO NÃO E VÁLIDO COMO GARANTIA DE MERCADORIA");
        jPanel1.add(lblRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 490, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 530));

        jMenu1.setMnemonic('p');
        jMenu1.setText("Opções");
        jMenu1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jMenuItem1.setMnemonic('c');
        jMenuItem1.setText("Cadastrar Cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencheOrcamento() {
        if (orcamento == null) {
            orcamento = new Orcamento();
        }
        if (cbTipoPagamento.getSelectedIndex() > 0) {
            orcamento.setTipoPagamento(tipoPagamento());
        }
        if (cbCliente.getSelectedIndex() > 0) {
            orcamento.setCliente((Cliente) cbCliente.getSelectedItem());
        }
        if (cbVendedor.getSelectedIndex() > 0) {
            orcamento.setVendedor((Vendedor) cbVendedor.getSelectedItem());
        }

    }

    private String tipoPagamento() {
        switch (cbTipoPagamento.getSelectedIndex()) {
            case 1:
//                orcamento.setTipoPagamento("VV");
//                cbTipoPagamento.setSelectedIndex(0);
//                cbTipoPagamento.requestFocus();

                return "VV";
            case 2:
//                orcamento.setTipoPagamento("VP");
//                cbTipoPagamento.setSelectedIndex(0);
//                cbTipoPagamento.requestFocus();

                return "VP";
            case 3:
//                venda.setTipoPagamento("VC");

//                cbTipoPagamento.setSelectedIndex(0);
//                cbTipoPagamento.requestFocus();
                return "VC";
        }
        return "";
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (cbTipoPagamento.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Tipo de Pagamento!");
            cbTipoPagamento.requestFocus();
            return;
        }
        if (cbVendedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Vendedor!");
            cbVendedor.requestFocus();
            return;
        }
        if (cbCliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Cliente!");
            cbCliente.requestFocus();
            return;
        }
        preencheOrcamento();

        ProdutoDAO pDAO = new ProdutoDAO();
        ProdutoTableModel ptm = new ProdutoTableModel(pDAO.list());
        Object o = TelaPesquisa.exibeTela(ptm, "Produto");
        if (o != null) {
            tfQuantidade.setText("1");
            produto = pDAO.checkExists("id", Integer.valueOf(String.valueOf(o))).get(0);
            lblDescricaoProduto.setText(produto.getDescricao());
            tfQuantidade.requestFocus();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (itensOrcamento == null) {
            itensOrcamento = new ArrayList<ItemOrcamento>();
        }
        if (produto == null) {
            jButton1ActionPerformed(evt);
            return;
        } else {
            if (tfQuantidade.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Informe a quantidade!");
                tfQuantidade.requestFocus();
                return;
            } else {
                ItemOrcamento it = new ItemOrcamento();
                it.setQuantidade(Double.parseDouble(tfQuantidade.getText().replace(",", ".")));
                it.setProduto(produto);
                it.setOrcamento(orcamento);
                it.setValorUni(produto.getPrecoVenda());
                if (it.getQuantidade() > it.getProduto().getQtdEstoque() && !it.getProduto().isServico()) {
                    JOptionPane.showMessageDialog(rootPane, "Quantidade Insuficiente!");
                    tfQuantidade.requestFocus();
                    return;
                }
                if (it.getQuantidade() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Quantidade não pode ser 0!");
                    tfQuantidade.requestFocus();
                    return;
                }
                if (verificaProdutoAdicionado()) {

                    return;
                }
                it.setOrdem(itensOrcamento.size() + 1);

                itensOrcamento.add(it);
                produto = null;
                lblDescricaoProduto.setText("");
                tfQuantidade.setText("");

            }

        }
        preencheTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean verificaProdutoAdicionado() {
        for (int i = 0; i < itensOrcamento.size(); i++) {
            if (itensOrcamento.get(i).getProduto().equals(produto)) {
                if (JOptionPane.showConfirmDialog(rootPane, "Produto Já Adicionado, Deseja Aumentar a Quantidade?",
                        "Produto Encontrado", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE)
                        == JOptionPane.YES_OPTION) {
                    double qtd = itensOrcamento.get(i).getQuantidade();
                    double nvQtd = Double.parseDouble(tfQuantidade.getText().replace(",", "."));
                    itensOrcamento.get(i).setQuantidade(qtd + nvQtd);

                    produto = null;
                    lblDescricaoProduto.setText("");
                    preencheTabela();
                }
                return true;
            }
        }
        return false;
    }

    private void tfQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton2ActionPerformed(null);
        }
    }//GEN-LAST:event_tfQuantidadeKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (itensOrcamento.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Não existe ítens!");
        } else {
            Integer ordem = 0;
            try {
                ordem = Integer.parseInt(JOptionPane.showInputDialog("Informe a Ordem Que deseja Cancelar: "));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro!");
                return;
            }
            if (ordem > 0) {
                for (int i = 0; i < itensOrcamento.size(); i++) {
                    if (itensOrcamento.get(i).getOrdem().equals(ordem)) {
                        itensOrcamento.remove(i);

                        break;
                    }
                }
            }
            preencheTabela();

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (valorTotal() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Orçamento está com valor 0!");
            return;
        }
        preencheTabela();

        if (itensOrcamento.size() > 0) {
            orcamento.setValorTotal(valorTotal());
            orcamento.setDesconto(Double.parseDouble(lblDesconto1.getText().replace(",", ".")));
            orcamento.setData(new Date());

            String dataString = lblDataVencimento.getText();
            try {
                DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                java.util.Date data;
                data = new java.util.Date(fmt.parse(dataString).getTime());
                orcamento.setDataValidade(data);
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }

            OrcamentoDAO oDAO = new OrcamentoDAO();
            oDAO.add(orcamento);
            for (ItemOrcamento itensOrc : itensOrcamento) {
                ItemOrcamentoDAO ioDAO = new ItemOrcamentoDAO();
                itensOrc.setOrcamento(orcamento);
                ioDAO.add(itensOrc);
            }

            if (JOptionPane.showConfirmDialog(rootPane, "Orçamento Realizado Com Sucesso!\nDeseja Imprimir?",
                    "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                HashMap parametros = new HashMap();
                parametros.put("sql", orcamento.getId());
                Util.imprimir("relatorios/reportOrcamento.jrxml", parametros);

            }

            limpaCampos();
            dispose();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe os ítens do Orçamento!");
        }

        limpaCampos();
    }//GEN-LAST:event_jButton4ActionPerformed

    private int qtdDias = -1;

    private void limpaCampos() {
        tfQuantidade.setText("");
        orcamento = new Orcamento();
        cbCliente.setSelectedIndex(0);
        cbVendedor.setSelectedIndex(0);
        cbTipoPagamento.setSelectedIndex(0);
        tfQuantidade.setText("1");
        itensOrcamento = new ArrayList<ItemOrcamento>();
        preencheTabela();
        preencheCliente();
        preencheVendedor();
        SimpleDateFormat dfdtData;
        dfdtData = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(dfdtData.format(new Date()));
        if (qtdDias == -1) {
            do {
                try {
                    qtdDias = Integer.parseInt(JOptionPane.showInputDialog("Inform a quantidade de dias de validade do Orçamento: "));
                } catch (Exception e) {
                    qtdDias = -1;
                }
            } while (qtdDias == -1);
        }
        Calendar c = Calendar.getInstance();
        c.setTime(new Date());
        c.add(Calendar.DATE, qtdDias);

        Date dataValidade = c.getTime();
        lblDataVencimento.setText(dfdtData.format(dataValidade));
    }

    private void cbTipoPagamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTipoPagamentoFocusLost
        // TODO add your handling code here:
        preencheTabela();

    }//GEN-LAST:event_cbTipoPagamentoFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        if (JOptionPane.showConfirmDialog(rootPane, "Deseja cancelar o Orçamento?", "Cancelar", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_OPTION) {
            cancelarOrcamento();
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        cancelarOrcamento();


    }//GEN-LAST:event_formWindowClosing

    private void cbClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbClienteFocusLost

    }//GEN-LAST:event_cbClienteFocusLost

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jPanel2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (Util.verificaPermissao("CE_CLIENTE", 1)) {
            TelaCliente tc = new TelaCliente();
            tc.setVisible(true);
            preencheCliente();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cancelarOrcamento() {
//        limpaCampos();
        dispose();
    }

    private double valorTotal() {
        double parcial = 0, total = 0, desconto = 0;
        for (ItemOrcamento itensOrc : itensOrcamento) {

            parcial += itensOrc.getParcial();
            desconto += itensOrc.getDesconto();

        }
        total = parcial - desconto;
        lblParcial.setText(String.format("%.2f", parcial));
        lblDesconto1.setText(String.format("%.2f", desconto));
        lblTotalFinal.setText(String.format("%.2f", total));
        return parcial;
    }

    private void preencheTabela() {
        if (itensOrcamento == null) {
            itensOrcamento = new ArrayList<>();
        }
        preencheOrcamento();
//        Collections.sort(itensVenda);
        for (int i = 0; i < itensOrcamento.size(); i++) {
            itensOrcamento.get(i).setOrdem(i + 1);
        }
        ItemOrcamentoTableModel iv = new ItemOrcamentoTableModel(itensOrcamento);
        tb.setModel(iv);
        valorTotal();
        FormataTamanhoColunasJTable.packColumns(tb, 1);
//        tb.setAutoCreateRowSorter(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaOrcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaOrcamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbTipoPagamento;
    private javax.swing.JComboBox cbVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDataVencimento;
    private javax.swing.JLabel lblDesconto1;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblParcial;
    private javax.swing.JLabel lblRazaoSocial;
    private javax.swing.JLabel lblRua;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTotalFinal;
    private javax.swing.JTable tb;
    private javax.swing.JFormattedTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables

    private void adicionaEstoque(String desc, double qtdEntrada, double qtdSaida, Produto produto) {
        Estoque e = new Estoque();
        EstoqueDAO eDAO = new EstoqueDAO();

        e.setData(new Date());
        e.setHora(new Date());
        e.setDescricao(desc);
        e.setProduto(produto);
        e.setQtdEntrada(qtdEntrada);
        e.setQtdSaida(qtdSaida);

        eDAO.add(e);
    }

}
