/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.telas;

import br.cartao.CartaoCredito;
import br.cartao.CartaoCreditoDAO;
import br.contasreceber.ContasReceber;
import br.contasreceber.ContasReceberDAO;
import br.livro.LivroCaixa;
import br.livro.LivroCaixaDAO;
import br.produto.Estoque;
import br.produto.EstoqueDAO;
import br.produto.Produto;
import br.produto.ProdutoDAO;
import br.util.FormataTamanhoColunasJTable;
import br.util.Util;
import br.venda.ItemVenda;
import br.venda.ItemVendaDAO;
import br.venda.Venda;
import br.venda.VendaCellRenderer;
import br.venda.VendaDAO;
import br.venda.VendaTableModel;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaListarVendas extends JDialog {

    /**
     * Creates new form TelaListarVendas
     */
    public TelaListarVendas() {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        SimpleDateFormat dfdtData;
        dfdtData = new SimpleDateFormat("dd/MM/yyyy");
        tfDataInicio.setText(dfdtData.format(new Date()));
        tfDataFim.setText(dfdtData.format(new Date()));
        btPesquisarActionPerformed(null);
        setTitle("Listar Vendas");

    }

    VendaDAO dao = new VendaDAO();

    private void preencheTabela(List<Venda> lista) {
        VendaTableModel vtm = new VendaTableModel(lista);
        tb.setModel(vtm);
        tb.setDefaultRenderer(Object.class, new VendaCellRenderer());
        FormataTamanhoColunasJTable.packColumns(tb, 1);
        tb.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        tfDataInicio = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfDataFim = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblVista = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPrazo = new javax.swing.JLabel();
        lblCartao = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 740, 250));

        try {
            tfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataInicio.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jPanel1.add(tfDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, -1));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel1.setText("Vendas Canceladas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, 20));

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/find.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel1.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 40, -1));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 20, 20));

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/cancel2.png"))); // NOI18N
        btSair.setToolTipText("Visualizar Venda");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel1.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 70, 50));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/delete.png"))); // NOI18N
        jButton6.setToolTipText("Cancelar Venda");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 70, 50));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel3.setText("Data Fim");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        try {
            tfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataFim.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jPanel1.add(tfDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 150, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel4.setText("Data Inicio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Totais"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel5.setText("Vendas à  Prazo.:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel6.setText("Vendas à  Cartão.:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        lblVista.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblVista.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblVista.setText("R$ 0,00");
        jPanel2.add(lblVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 90, 20));

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel8.setText("Vendas à  Vista.:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        lblPrazo.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblPrazo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPrazo.setText("R$ 0,00");
        jPanel2.add(lblPrazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 90, 20));

        lblCartao.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblCartao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblCartao.setText("R$ 0,00");
        jPanel2.add(lblCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 90, 20));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 240, 90));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/delete.png"))); // NOI18N
        jButton7.setToolTipText("Cancelar Venda");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 70, 50));

        btImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/print.png"))); // NOI18N
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });
        jPanel1.add(btImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if (!tfDataInicio.getText().equals("  /  /    ") && !tfDataFim.getText().equals("  /  /    ")) {
            java.util.Date dataIni = null, dataFim = null;
            try {
                DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                dataIni = new java.util.Date(fmt.parse(tfDataInicio.getText()).getTime());
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
            try {
                DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                dataFim = new java.util.Date(fmt.parse(tfDataFim.getText()).getTime());
            } catch (ParseException ex) {
                System.out.println(ex.getMessage());
            }
            if (dataIni == null && dataFim == null) {
                preencheTabela(new ArrayList<Venda>());
            } else {
                List<Venda> listaVenda = new ArrayList<>();
                if(Util.verificaPermissao("VISUAL_APENAS_VENDAS_REAL_PELO_USU", 0)){
                    listaVenda = dao.listVendaEntreDatasPorUsuario(dataIni, dataFim);
                } else {
                    listaVenda = dao.listVendaEntreDatas(dataIni, dataFim);
                }
                
                preencheTabela(listaVenda);
                preencheTotais(listaVenda);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe a Data Inicio e Fim!");
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void preencheTotais(List<Venda> lista) {
        double tvv = 0, tvp = 0, tvc = 0;
        int qtdVCanceladas = 0;
        for (Venda v : lista) {
            if (v.isCancelada()) {
                qtdVCanceladas++;
            } else {
                tvv += v.getVlVista();
                tvp += v.getVlPromissoria();
                tvc += v.getVlCartao();
            }
        }
        lblCartao.setText(Util.acertarNumero(tvc));
        lblPrazo.setText(Util.acertarNumero(tvp));
        lblVista.setText(Util.acertarNumero(tvv));

    }

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (Util.verificaPermissao("CANCEL_VENDA", 1)) {
            int i = tb.getSelectedRow();
            if (i >= 0) {
                VendaTableModel vtm = (VendaTableModel) tb.getModel();
                Venda v = vtm.getValueAt(i);
                VendaDAO dao = new VendaDAO();
                if (v.isCancelada()) {
                    JOptionPane.showMessageDialog(rootPane, "Venda Já Está Cancelada!");
                } else {
                    if (JOptionPane.showConfirmDialog(rootPane, "Deseja Cancelar a Venda: "
                            + Util.decimalFormat().format(v.getId()) + "?",
                            "", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                        v.setCancelada(true);
                        dao.update(v);

                        //cancela itens, retornando suas quantidades ao estoque
                        ProdutoDAO pDAO = new ProdutoDAO();
                        ItemVendaDAO ivDAO = new ItemVendaDAO();
                        List<ItemVenda> itensVenda = ivDAO.checkExists("venda", v);
                        for (ItemVenda itensVenda1 : itensVenda) {
                            if (!itensVenda1.isCancelado()) {
                                Produto p1 = pDAO.checkExists("id", itensVenda1.getProduto().getId()).get(0);
                                p1.setQtdEstoque(p1.getQtdEstoque() + itensVenda1.getQuantidade());
                                pDAO.update(p1);
                                Util.adicionaEstoque("CANCELAMENTO DE VENDA", itensVenda1.getQuantidade(), 0, p1);
                            }
                            itensVenda1.setCancelado(true);
                            itensVenda1.setVenda(v);
                            ivDAO.add(itensVenda1);
                        }

                        //cancela livro de caixa relacionado a venda
                        LivroCaixaDAO lDAO = new LivroCaixaDAO();
                        List<LivroCaixa> listCaixa = lDAO.checkExists("venda", v);
                        for (LivroCaixa c : listCaixa) {
                            lDAO.remove(c);
                        }

                        //cancela contas a receber relacionadas a venda
                        ContasReceberDAO crDAO = new ContasReceberDAO();
                        List<ContasReceber> listCR = crDAO.checkExists("venda", v);
                        for (ContasReceber cr : listCR) {
                            crDAO.remove(cr);
                        }

                        //cancela cartão de credito relacionado a venda
                        CartaoCreditoDAO ccdDAO = new CartaoCreditoDAO();
                        List<CartaoCredito> listCCD = ccdDAO.checkExists("venda", v);
                        for (CartaoCredito ccd : listCCD) {
                            ccdDAO.remove(ccd);
                        }
                        btPesquisarActionPerformed(evt);

                    }
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione uma Venda!");
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    private void tbKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btImprimirActionPerformed(null);
        }
    }//GEN-LAST:event_tbKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed

    }//GEN-LAST:event_jPanel1KeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

    }//GEN-LAST:event_formKeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        if (Util.verificaPermissao("V_VENDA", 1)) {
            int i = tb.getSelectedRow();
            if (i >= 0) {
                VendaTableModel vtm = (VendaTableModel) tb.getModel();
                Venda v = vtm.getValueAt(i);
                VendaDAO dao = new VendaDAO();
                if (v.isCancelada()) {
                    JOptionPane.showMessageDialog(rootPane, "Venda Está Cancelada!");
                } else {
                    HashMap parametros = new HashMap();
                    parametros.put("sql", v.getId());
                    Util.imprimir("relatorios/reportVenda.jrxml", parametros);
                }

            }
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListarVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListarVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSair;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCartao;
    private javax.swing.JLabel lblPrazo;
    private javax.swing.JLabel lblVista;
    private javax.swing.JTable tb;
    private javax.swing.JFormattedTextField tfDataFim;
    private javax.swing.JFormattedTextField tfDataInicio;
    // End of variables declaration//GEN-END:variables
}
