/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.telas;

import br.cliente.Cliente;
import br.cliente.ClienteDAO;
import br.produto.ProdutoTableModel;
import br.produto.Produto;
import br.produto.ProdutoDAO;
import br.util.FormataTamanhoColunasJTable;
import br.venda.ItemVenda;
import br.venda.ItemVendaTableModel;
import br.venda.Venda;
import br.vendedor.Vendedor;
import br.vendedor.VendedorDAO;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaVenda extends javax.swing.JDialog {

    private List<ItemVenda> itensVenda;
    private Produto produto;
    private Venda venda = new Venda();

    /**
     * Creates new form TelaVenda
     */
    public TelaVenda() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        preencheCliente();
        preencheVendedor();
        SimpleDateFormat dfdtData;
        dfdtData = new SimpleDateFormat("dd/MM/yyyy");
        lblData.setText(dfdtData.format(new Date()));
        preencheTabela();
    }

    public void preencheVendedor() {
        cbVendedor.removeAllItems();
        cbVendedor.addItem("--");
        VendedorDAO vDAO = new VendedorDAO();
        List<Vendedor> lista = vDAO.list();
        Collections.sort(lista);
        for (Vendedor v : lista) {
            cbVendedor.addItem(v);
        }
    }

    public void preencheCliente() {
        cbCliente.removeAllItems();
        cbCliente.addItem("--");
        ClienteDAO cDAO = new ClienteDAO();
        List<Cliente> lista = cDAO.list();
        Collections.sort(lista);
        for (Cliente c : lista) {
            cbCliente.addItem(c);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        lbTexto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbTipoPagamento = new javax.swing.JComboBox();
        cbVendedor = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbCliente = new javax.swing.JComboBox();
        btNovo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblDescricaoProduto = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfQuantidade = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        lblParcial = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTotalFinal = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDesconto1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTexto.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lbTexto.setText("Vendas");
        jPanel4.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 182, 659, 201));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Tipo Pagamento.: *");

        cbTipoPagamento.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Venda à Vista", "Venda à Prazo", "Venda à Cartão" }));
        cbTipoPagamento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbTipoPagamentoFocusLost(evt);
            }
        });

        cbVendedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbVendedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "Venda à Vista", "Venda à Prazo", "Venda à Cartão" }));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Vendedor.: *");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Cliente.: *");

        cbCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cbCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));

        btNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/new.png"))); // NOI18N
        btNovo.setToolTipText("Novo Cliente");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Data.: *");

        lblData.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblData.setText("Data.: *");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btNovo)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(lblData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/codbarras.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, -1, 55));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setText("Quantidade.: *");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, 20));

        lblDescricaoProduto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblDescricaoProduto.setText(" ");
        jPanel1.add(lblDescricaoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 260, 20));

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setText("Descrição.: *");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 121, -1, 20));

        tfQuantidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tfQuantidade.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfQuantidadeKeyPressed(evt);
            }
        });
        jPanel1.add(tfQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/add.png"))); // NOI18N
        jButton2.setToolTipText("Adicionar Produto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 50, 40));

        lblParcial.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblParcial.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 390, 90, 20));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel8.setText("Total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, -1, 20));

        lblTotalFinal.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblTotalFinal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblTotalFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 90, 20));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Desc.:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, -1, 20));

        lblDesconto1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        lblDesconto1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblDesconto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 90, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/delete (1).png"))); // NOI18N
        jButton3.setToolTipText("Cancelar Produto");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 50, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/money.png"))); // NOI18N
        jButton4.setToolTipText("Finalizar Venda");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 50, 40));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/cancel.png"))); // NOI18N
        jButton5.setToolTipText("Cancelar Venda");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 50, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 690, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        TelaCliente tc = new TelaCliente();
        tc.setVisible(true);
        preencheCliente();
    }//GEN-LAST:event_btNovoActionPerformed

    private void preencheVenda() {
        if (venda == null) {
            venda = new Venda();
        }
        venda.setTipoPagamento(tipoPagamento());
        
    }
    
    private String tipoPagamento(){
        switch (cbTipoPagamento.getSelectedIndex()) {
            case 1:
//                venda.setTipoPagamento("VV");
                return "VV";
            case 2:
//                venda.setTipoPagamento("VP");
                return "VP";
            case 3:
//                venda.setTipoPagamento("VC");
                return "VC";
        }
        return "";
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (cbTipoPagamento.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Tipo de Pagamento!");
            cbTipoPagamento.requestFocus();
            return;
        }
        if (cbVendedor.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Vendedor!");
            cbVendedor.requestFocus();
            return;
        }
        if (cbCliente.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Cliente!");
            cbCliente.requestFocus();
            return;
        }
        preencheVenda();

        ProdutoDAO pDAO = new ProdutoDAO();
        ProdutoTableModel ptm = new ProdutoTableModel(pDAO.list());
        Object o = TelaPesquisa.exibeTela(ptm, "Produto");
        if (o != null) {
            tfQuantidade.setText("1");
            produto = pDAO.checkExists("id", Integer.valueOf(String.valueOf(o))).get(0);
            lblDescricaoProduto.setText(produto.getDescricao());
            tfQuantidade.requestFocus();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (itensVenda == null) {
            itensVenda = new ArrayList<ItemVenda>();
        }
        if (produto == null) {
            jButton1ActionPerformed(evt);
            return;
        } else {
            if (tfQuantidade.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Informe a quantidade!");
                tfQuantidade.requestFocus();
                return;
            } else {
                ItemVenda it = new ItemVenda();
                it.setQuantidade(Double.parseDouble(tfQuantidade.getText().replace(",", ".")));
                it.setProduto(produto);
                it.setVenda(venda);
                if (it.getQuantidade() > it.getProduto().getQtdEstoque() && !it.getProduto().isServico()) {
                    JOptionPane.showMessageDialog(rootPane, "Quantidade Insuficiente!");
                    tfQuantidade.requestFocus();
                    return;
                }
                if (it.getQuantidade() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Quantidade não pode ser 0!");
                    tfQuantidade.requestFocus();
                    return;
                }
                if (verificaProdutoAdicionado()) {
                    return;
                }
                it.setOrdem(itensVenda.size() + 1);
                itensVenda.add(it);
                produto = null;
                lblDescricaoProduto.setText("");

            }

        }
        preencheTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean verificaProdutoAdicionado() {
        for (int i = 0; i < itensVenda.size(); i++) {
            if (itensVenda.get(i).getProduto().equals(produto) && !itensVenda.get(i).isCancelado()) {
                if (JOptionPane.showConfirmDialog(rootPane, "Produto Já Adicionado, Deseja Aumentar a Quantidade?",
                        "Produto Encontrado", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE)
                        == JOptionPane.YES_OPTION) {
                    double qtd = itensVenda.get(i).getQuantidade();
                    double nvQtd = Double.parseDouble(tfQuantidade.getText().replace(",", "."));
                    itensVenda.get(i).setQuantidade(qtd + nvQtd);
                    produto = null;
                    lblDescricaoProduto.setText("");
                    preencheTabela();
                }
                return true;
            }
        }
        return false;
    }

    private void tfQuantidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQuantidadeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButton2ActionPerformed(null);
        }
    }//GEN-LAST:event_tfQuantidadeKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (itensVenda.size() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Não existe ítens!");
        } else {
            Integer ordem = 0;
            try {
                ordem = Integer.parseInt(JOptionPane.showInputDialog("Informe a Ordem Que deseja Cancelar: "));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro!");
                return;
            }
            if (ordem > 0) {
                for (int i = 0; i < itensVenda.size(); i++) {
                    if (itensVenda.get(i).getOrdem().equals(ordem)) {
                        itensVenda.get(i).setCancelado(true);
                        break;
                    }
                }
            }
            preencheTabela();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        preencheTabela();
        if (itensVenda.size() > 0) {
            TelaFechaVenda.exibeFechamento(tipoPagamento(), valorTotal());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe os ítens da venda!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void cbTipoPagamentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbTipoPagamentoFocusLost
        // TODO add your handling code here:
        preencheTabela();
    }//GEN-LAST:event_cbTipoPagamentoFocusLost

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private double valorTotal() {
        double parcial = 0, total = 0, desconto = 0;
        for (ItemVenda itensVenda1 : itensVenda) {
            if (!itensVenda1.isCancelado()) {
                parcial += itensVenda1.getParcial();
                desconto += itensVenda1.getDesconto();
            }
        }
        total = parcial - desconto;
        lblParcial.setText(String.valueOf(parcial));
        lblDesconto1.setText(String.valueOf(desconto));
        lblTotalFinal.setText(String.valueOf(total));
        return total;
    }

    private void preencheTabela() {
        if (itensVenda == null) {
            itensVenda = new ArrayList<>();
        }
        preencheVenda();
//        Collections.sort(itensVenda);
        ItemVendaTableModel iv = new ItemVendaTableModel(itensVenda);
        tb.setModel(iv);
        valorTotal();
        FormataTamanhoColunasJTable.packColumns(tb, 1);
    }
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JComboBox cbCliente;
    private javax.swing.JComboBox cbTipoPagamento;
    private javax.swing.JComboBox cbVendedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDesconto1;
    private javax.swing.JLabel lblDescricaoProduto;
    private javax.swing.JLabel lblParcial;
    private javax.swing.JLabel lblTotalFinal;
    private javax.swing.JTable tb;
    private javax.swing.JFormattedTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
