/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.telas;

import br.caixageral.CaixaGeral;
import br.caixageral.CaixaGeralDAO;
import br.contabancaria.ContaBancaria;
import br.contabancaria.ContaBancariaDAO;
import br.contabancaria.ItemContaBancaria;
import br.contabancaria.ItemContaBancariaDAO;
import br.util.Util;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaTransferencia extends javax.swing.JDialog {

    //conta origen caixa geral
    public TelaTransferencia() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        rbContaBancaria.setSelected(true);
        rbCaixaGeral.setEnabled(false);
        cbContaDestino.setEnabled(false);
        SimpleDateFormat dfdtData;
        dfdtData = new SimpleDateFormat("dd/MM/yyyy");
        tfData.setText(dfdtData.format(new Date()));
        tfData.setEnabled(false);

        contaOrigemBancaria = null;
        contaOrigemCaixaGeral = new CaixaGeral();

        cbContaOrigem.removeAllItems();
        cbContaOrigem.addItem("CAIXA GERAL");
        cbContaOrigem.setEnabled(false);
        cbContaDestino.setEnabled(true);
        preencheConta();
        CaixaGeralDAO dao = new CaixaGeralDAO();
        saldoConta = dao.saldoConta();
        tfSaldo.setText(Util.acertarNumero(saldoConta));

    }

    //conta origem conta bancaria
    public TelaTransferencia(ContaBancaria cb) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        cbContaOrigem.addItem(cb);
        cbContaOrigem.setSelectedItem(cb);
        cbContaOrigem.setEnabled(false);

        SimpleDateFormat dfdtData;
        dfdtData = new SimpleDateFormat("dd/MM/yyyy");
        tfData.setText(dfdtData.format(new Date()));
        tfData.setEnabled(false);
        rbCaixaGeral.setSelected(true);
        contaOrigemBancaria = cb;
        contaOrigemCaixaGeral = null;

        ItemContaBancariaDAO iDAO = new ItemContaBancariaDAO();
        this.saldoConta = iDAO.SaldoConta(cb);
        tfSaldo.setText(Util.acertarNumero(saldoConta));
    }

    private ContaBancaria contaOrigemBancaria = null;
    private CaixaGeral contaOrigemCaixaGeral = null;
    private double saldoConta = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbTexto = new javax.swing.JLabel();
        cbContaOrigem = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tfValor = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        tfData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbCaixaGeral = new javax.swing.JRadioButton();
        rbContaBancaria = new javax.swing.JRadioButton();
        cbContaDestino = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfSaldo = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTexto.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lbTexto.setText("Transferência");
        jPanel1.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        cbContaOrigem.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        cbContaOrigem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        cbContaOrigem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbContaOrigemFocusLost(evt);
            }
        });
        jPanel1.add(cbContaOrigem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 500, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel2.setText("Conta Origem.:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        tfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfValor.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jPanel1.add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 160, -1));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel3.setText("Valor.: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        try {
            tfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfData.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jPanel1.add(tfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 160, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel4.setText("Data.:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Transferência para"));

        buttonGroup1.add(rbCaixaGeral);
        rbCaixaGeral.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 11)); // NOI18N
        rbCaixaGeral.setText("Caixa Geral");
        rbCaixaGeral.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbCaixaGeralItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbContaBancaria);
        rbContaBancaria.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 11)); // NOI18N
        rbContaBancaria.setText("Conta Bancária");
        rbContaBancaria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbContaBancariaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(rbCaixaGeral)
                .addGap(27, 27, 27)
                .addComponent(rbContaBancaria)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCaixaGeral)
                    .addComponent(rbContaBancaria))
                .addGap(16, 16, 16))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 340, 80));

        cbContaDestino.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        cbContaDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        cbContaDestino.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbContaDestinoFocusLost(evt);
            }
        });
        jPanel1.add(cbContaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 500, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel5.setText("Conta Destino.:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/cancel2.png"))); // NOI18N
        jButton1.setToolTipText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 350, 60, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/ok.png"))); // NOI18N
        jButton2.setToolTipText("Transferir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, -1, 40));

        tfSaldo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfSaldo.setEnabled(false);
        tfSaldo.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jPanel1.add(tfSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 150, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel6.setText("Saldo.: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 60, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbContaOrigemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbContaOrigemFocusLost

    }//GEN-LAST:event_cbContaOrigemFocusLost

    private void cbContaDestinoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbContaDestinoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_cbContaDestinoFocusLost

    private void rbCaixaGeralItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbCaixaGeralItemStateChanged
        if (rbCaixaGeral.isSelected()) {
            cbContaDestino.setSelectedIndex(0);
            cbContaDestino.setEnabled(false);
        } else {
            cbContaDestino.setEnabled(true);
            preencheConta();
        }
    }//GEN-LAST:event_rbCaixaGeralItemStateChanged

    private void rbContaBancariaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbContaBancariaItemStateChanged
        if (rbCaixaGeral.isSelected()) {
            cbContaDestino.setSelectedIndex(0);
            cbContaDestino.setEnabled(false);
        } else {
            cbContaDestino.setEnabled(true);
            preencheConta();
        }
    }//GEN-LAST:event_rbContaBancariaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma a Transferência?",
                "", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }

        if (tfValor.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Informe o Valor!");
            return;
        }

        double valor = 0;
        try {
            valor = Double.parseDouble(tfValor.getText().replaceAll(",", "."));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "ERRO no valor!");
            return;
        }
        if (valor <= 0) {
            JOptionPane.showMessageDialog(rootPane, "O Valor deve ser Maior que 0!");
            tfValor.requestFocus();
            return;
        }
        if (valor > saldoConta) {
            JOptionPane.showMessageDialog(rootPane, "Valor maior que saldo da conta!");
            tfValor.requestFocus();
            return;
        }

        //se a conta de origem for uma conta bancária
        if (contaOrigemBancaria != null) {

            if (rbCaixaGeral.isSelected()) {
                //se for para caixa geral
                ItemContaBancaria icb = new ItemContaBancaria();
                icb.setData(new Date());
                icb.setDescricao("TRANSFERÊNCIA PARA CAIXA GERAL");
                icb.setEntrada(0);
                icb.setSaida(valor);
                icb.setContaBancaria(contaOrigemBancaria);

                ItemContaBancariaDAO iDAO = new ItemContaBancariaDAO();
                iDAO.add(icb);

                CaixaGeral cg = new CaixaGeral();
                cg.setData(new Date());
                cg.setDescricao("TRANSFERÊNCIA DA CONTA " + contaOrigemBancaria.toString());
                cg.setValorEntrada(valor);
                cg.setValorSaida(0);
                CaixaGeralDAO cgDAO = new CaixaGeralDAO();
                cgDAO.add(cg);

            } else {
                if (cbContaDestino.getSelectedIndex() == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Informe a Conta Destino!");
                    return;
                }
                //se for para conta bancária
                ContaBancaria contaDestino = (ContaBancaria) cbContaDestino.getSelectedItem();
                ItemContaBancariaDAO iDAO = new ItemContaBancariaDAO();

                ItemContaBancaria icb = new ItemContaBancaria();
                icb.setData(new Date());
                icb.setDescricao("TRANSFERÊNCIA PARA CONTA " + contaDestino.toString());
                icb.setEntrada(0);
                icb.setSaida(valor);
                icb.setContaBancaria(contaOrigemBancaria);
                iDAO.add(icb);

                ItemContaBancaria icb2 = new ItemContaBancaria();
                icb2.setData(new Date());
                icb2.setDescricao("TRANSFERÊNCIA DA CONTA " + contaOrigemBancaria.toString());
                icb2.setEntrada(valor);
                icb2.setSaida(0);
                icb2.setContaBancaria(contaDestino);
                iDAO.add(icb2);
            }

        } else {
            //se a conta de origem for um caixa geral
            if (cbContaDestino.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(rootPane, "Informe a Conta Destino!");
                return;
            }

            ContaBancaria contaDestino = (ContaBancaria) cbContaDestino.getSelectedItem();

            CaixaGeralDAO cgDAO = new CaixaGeralDAO();
            CaixaGeral cg = new CaixaGeral();
            cg.setData(new Date());
            cg.setDescricao("TRANSFERÊNCIA PARA CONTA " + contaDestino.toString());
            cg.setValorSaida(valor);
            cg.setValorEntrada(0);
            cgDAO.add(cg);

            ItemContaBancaria icb2 = new ItemContaBancaria();
            icb2.setData(new Date());
            icb2.setDescricao("TRANSFERÊNCIA DE CAIXA GERAL");
            icb2.setEntrada(valor);
            icb2.setSaida(0);
            icb2.setContaBancaria(contaDestino);
            ItemContaBancariaDAO iDAO = new ItemContaBancariaDAO();
            iDAO.add(icb2);

        }
        JOptionPane.showMessageDialog(rootPane, "Transferência Realizada com Sucesso!");
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    public void preencheConta() {
        ContaBancariaDAO dao = new ContaBancariaDAO();
        cbContaDestino.removeAllItems();
        cbContaDestino.addItem("--");
        for (ContaBancaria cb : dao.list()) {
            if (contaOrigemBancaria != null) {
                if (!(contaOrigemBancaria).equals(cb)) {
                    cbContaDestino.addItem(cb);
                }
            } else {
                cbContaDestino.addItem(cb);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaTransferencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaTransferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbContaDestino;
    private javax.swing.JComboBox cbContaOrigem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JRadioButton rbCaixaGeral;
    private javax.swing.JRadioButton rbContaBancaria;
    private javax.swing.JFormattedTextField tfData;
    private javax.swing.JFormattedTextField tfSaldo;
    private javax.swing.JFormattedTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
