package br.telas;

import br.contabancaria.ContaBancaria;
import br.contabancaria.ContaBancariaDAO;
import br.contabancaria.ItemContaBancaria;
import br.contabancaria.ItemContaBancariaCellRenderer;
import br.contabancaria.ItemContaBancariaDAO;
import br.contabancaria.ItemContaBancariaTableModel;
import br.contaspagar.ContaPagarCellRenderer;
import br.contaspagar.ContasPagar;
import br.contaspagar.ContasPagarDAO;
import br.contaspagar.ContasPagarTableModel;
import br.contasreceber.ContasReceber;
import br.contasreceber.ContasReceberDAO;
import br.fornecedor.Fornecedor;
import br.fornecedor.FornecedorDAO;
import br.util.FormataTamanhoColunasJTable;
import br.util.Util;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaMovimentacaoContaBancaria extends javax.swing.JDialog {
    
    public TelaMovimentacaoContaBancaria() {
        initComponents();
        setTitle("Movimentação Conta Bancária");
        setModal(true);
        setLocationRelativeTo(null);
        preencheConta();
        preencheTabela(new ArrayList<ItemContaBancaria>());
        
    }
    
    public void preencheConta() {
        ContaBancariaDAO dao = new ContaBancariaDAO();
        List<ContaBancaria> list = dao.list();
        Collections.sort(list);
        for (ContaBancaria cb : list) {
            cbConta.addItem(cb);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btContas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblBloqueado = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        btNovo3 = new javax.swing.JButton();
        btRemover = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btPesquisar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbConta = new javax.swing.JComboBox();
        tfDataInicio = new javax.swing.JFormattedTextField();
        tfDataFim = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        lblSaida = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btTransferir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbContas.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        tbContas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbContas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbContasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbContas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 510, 310));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel4.setText("Bloqueado.:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        lblBloqueado.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblBloqueado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBloqueado.setText("0,00");
        jPanel1.add(lblBloqueado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 80, -1));

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/pen.png"))); // NOI18N
        btEdit.setToolTipText("Editar ");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });
        jPanel1.add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 43, -1));

        btNovo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/new.png"))); // NOI18N
        btNovo3.setToolTipText("Nova ");
        btNovo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovo3ActionPerformed(evt);
            }
        });
        jPanel1.add(btNovo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 43, -1));

        btRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/delete.png"))); // NOI18N
        btRemover.setToolTipText("Excluir ");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });
        jPanel1.add(btRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 43, -1));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel3.setText("Bloqueado");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, 20));

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 20, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/close.png"))); // NOI18N
        jButton1.setToolTipText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 40, 40));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/find.png"))); // NOI18N
        btPesquisar.setToolTipText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(btPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 40, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel2.setText("Conta.:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cbConta.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        cbConta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--" }));
        cbConta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbContaFocusLost(evt);
            }
        });
        jPanel2.add(cbConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 400, -1));

        try {
            tfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataInicio.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jPanel2.add(tfDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 110, -1));

        try {
            tfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfDataFim.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jPanel2.add(tfDataFim, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 110, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel5.setText("Dt. Fim:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel6.setText("Dt. Inicio:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 80));

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel7.setText("Valor Entradas.: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel8.setText("Valor Saídas.: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel9.setText("Saldo.:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        lblEntrada.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblEntrada.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblEntrada.setText("0,00");
        jPanel1.add(lblEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 80, -1));

        lblSaida.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblSaida.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaida.setText("0,00");
        jPanel1.add(lblSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 80, -1));

        lblSaldo.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        lblSaldo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSaldo.setText("0,00");
        jPanel1.add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, 80, -1));

        btTransferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/transfer.png"))); // NOI18N
        btTransferir.setToolTipText("Transferência Entre Contas");
        btTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferirActionPerformed(evt);
            }
        });
        jPanel1.add(btTransferir, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preencheTabela(List<ItemContaBancaria> contas) {
        Collections.sort(contas);
        ItemContaBancariaTableModel crtm = new ItemContaBancariaTableModel(contas);
        tbContas.setModel(crtm);
        FormataTamanhoColunasJTable.packColumns(tbContas, 1);
        tbContas.setAutoCreateRowSorter(true);
        double valorDebito = 0, valorPago = 0;
        
        tbContas.setAutoCreateRowSorter(true);
        tbContas.setDefaultRenderer(Object.class,
                new ItemContaBancariaCellRenderer());
        
        double entrada = 0, saida = 0, bloqueado = 0;
        for (ItemContaBancaria icb : contas) {
            if (icb.isBloqueada()) {
                double valor = (icb.getEntrada() == 0 ? icb.getSaida() : icb.getEntrada());
                bloqueado += valor;
            } else {
                entrada += icb.getEntrada();
                saida += icb.getSaida();
            }
        }
        lblBloqueado.setText(Util.acertarNumero(bloqueado));
        lblEntrada.setText(Util.acertarNumero(entrada));
        lblSaida.setText(Util.acertarNumero(saida));
        lblSaldo.setText(Util.acertarNumero(entrada - saida));
        
    }

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        int i = tbContas.getSelectedRow();
        if (i >= 0) {
            ItemContaBancariaTableModel itm = (ItemContaBancariaTableModel) tbContas.getModel();
            ItemContaBancaria icb = itm.getValueAt(i);
            TelaMoviCadEditaContaBancaria tela = new TelaMoviCadEditaContaBancaria(icb);
            tela.setVisible(true);
            btPesquisarActionPerformed(null);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Ítem!");
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btNovo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovo3ActionPerformed
        if (cbConta.getSelectedIndex() > 0) {
            TelaMoviCadEditaContaBancaria tmcrcb
                    = new TelaMoviCadEditaContaBancaria((ContaBancaria) cbConta.getSelectedItem());
            tmcrcb.setVisible(true);
            btPesquisarActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe a Conta!");
        }
    }//GEN-LAST:event_btNovo3ActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        int i = tbContas.getSelectedRow();
        if (i >= 0) {
            ItemContaBancariaTableModel itm = (ItemContaBancariaTableModel) tbContas.getModel();
            ItemContaBancaria icb = itm.getValueAt(i);
            if (JOptionPane.showConfirmDialog(rootPane, "Deseja Excluir o Item?",
                    "EXCLUIR", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                ItemContaBancariaDAO ibDAO = new ItemContaBancariaDAO();
                ibDAO.remove(icb);
                
                btPesquisarActionPerformed(null);
            }
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione o Ítem!");
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void tbContasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbContasKeyPressed

    }//GEN-LAST:event_tbContasKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if (cbConta.getSelectedIndex() > 0) {
            
            Date iniDate = null, endDate = null;
            if (!tfDataInicio.getText().equals("  /  /    ")) {
                
                iniDate = Util.verificaData(tfDataInicio.getText());
                
                if (iniDate == null) {
                    JOptionPane.showMessageDialog(rootPane, "Data Inicial Incorreta!");
                    return;
                }
                
                endDate = Util.verificaData(tfDataFim.getText());
                if (endDate == null) {
                    JOptionPane.showMessageDialog(rootPane, "Data Fim Incorreta!");
                    return;
                }
            }
            
            ItemContaBancariaDAO crDAO = new ItemContaBancariaDAO();
            preencheTabela(crDAO.listaContas(
                    cbConta.getSelectedIndex() == 0 ? null : (ContaBancaria) cbConta.getSelectedItem(), iniDate, endDate));
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe a Conta!");
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void cbContaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbContaFocusLost

    }//GEN-LAST:event_cbContaFocusLost

    private void btTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferirActionPerformed
        
        if (cbConta.getSelectedIndex() > 0) {
            
            TelaTransferencia tt = new TelaTransferencia((ContaBancaria) cbConta.getSelectedItem());
            tt.setVisible(true);
            btPesquisarActionPerformed(evt);
            
        } else {
            JOptionPane.showMessageDialog(rootPane, "Informe a Conta!");
        }
    }//GEN-LAST:event_btTransferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacaoContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacaoContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacaoContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMovimentacaoContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMovimentacaoContaBancaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btContas;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btNovo3;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btTransferir;
    private javax.swing.JComboBox cbConta;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBloqueado;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblSaida;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tbContas;
    private javax.swing.JFormattedTextField tfDataFim;
    private javax.swing.JFormattedTextField tfDataInicio;
    // End of variables declaration//GEN-END:variables
}
