/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.telas;

import br.contabancaria.ContaBancaria;
import br.contabancaria.ContaBancariaDAO;
import br.contabancaria.ContaBancariaTableModel;
import br.contabancaria.ItemContaBancaria;
import br.contabancaria.ItemContaBancariaDAO;
import br.util.Util;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaMoviCadEditaContaBancaria extends javax.swing.JDialog {

    /**
     * Creates new form TelaCliente
     */
    public TelaMoviCadEditaContaBancaria(ContaBancaria cb) {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        setTitle("Adiciona Item de Conta Bancária");
        limpaCampos();
        contaBancaria = cb;
        rbEntrada.setSelected(true);
        tfConta.setText(cb.toString());
        SimpleDateFormat dfdtData;
        dfdtData = new SimpleDateFormat("dd/MM/yyyy");
        tfData.setText(dfdtData.format(new Date()));
    }
    
    public TelaMoviCadEditaContaBancaria(ItemContaBancaria ib) {
        initComponents();
        setModal(true);
        setLocationRelativeTo(null);
        setTitle("Edita Item de Conta Bancária");
        limpaCampos();
        itemContaBancaria = ib;
        if(ib.getEntrada()>0){
            rbEntrada.setSelected(true);
            tfValor.setText(Util.acertarNumero(ib.getEntrada()));
        } else {
            rbSaida.setSelected(true);
            tfValor.setText(Util.acertarNumero(ib.getSaida()));
        }
        cbBloqueado.setSelected(ib.isBloqueada());
        contaBancaria = ib.getContaBancaria();
        tfConta.setText(ib.getContaBancaria().toString());
        SimpleDateFormat dfdtData;
        dfdtData = new SimpleDateFormat("dd/MM/yyyy");
        tfData.setText(dfdtData.format(ib.getData()));
        tfDescricao.setText(ib.getDescricao());
        
    }
    
    public TelaMoviCadEditaContaBancaria(){
        initComponents();
    }

    private ContaBancaria contaBancaria;
    private ItemContaBancaria itemContaBancaria;
    private ItemContaBancariaDAO dao = new ItemContaBancariaDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        lbTexto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfConta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        tfValor = new javax.swing.JFormattedTextField();
        tfData = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        rbSaida = new javax.swing.JRadioButton();
        rbEntrada = new javax.swing.JRadioButton();
        cbBloqueado = new javax.swing.JCheckBox();
        tfDescricao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTexto.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lbTexto.setText("Item Conta Bancária");
        jPanel4.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 40));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/close.png"))); // NOI18N
        btCancelar.setToolTipText("Sair");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 43, 41));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Descrição.: *");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        tfConta.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tfConta.setEnabled(false);
        jPanel1.add(tfConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 380, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Valor: *");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/pataverde.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 43, -1));

        jLabel30.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel30.setText("Conta Bancária.: *");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        tfValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        tfValor.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        tfValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfValorFocusLost(evt);
            }
        });
        jPanel1.add(tfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 160, -1));

        try {
            tfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfData.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        tfData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfDataFocusLost(evt);
            }
        });
        jPanel1.add(tfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 160, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 12)); // NOI18N
        jLabel4.setText("Data.:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        rbSaida.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbSaida);
        rbSaida.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 11)); // NOI18N
        rbSaida.setText("Saída");
        jPanel1.add(rbSaida, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        rbEntrada.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbEntrada);
        rbEntrada.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 11)); // NOI18N
        rbEntrada.setText("Entrada");
        jPanel1.add(rbEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        cbBloqueado.setBackground(new java.awt.Color(255, 255, 255));
        cbBloqueado.setFont(new java.awt.Font("Bitstream Vera Sans Mono", 0, 11)); // NOI18N
        cbBloqueado.setText("Valor Bloqueado");
        jPanel1.add(cbBloqueado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 150, -1));

        tfDescricao.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel1.add(tfDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 380, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if (itemContaBancaria == null) {
            itemContaBancaria = new ItemContaBancaria();
        }
        if (Util.chkVazio(tfDescricao.getText(), tfValor.getText(), tfData.getText())) {

            double valor = 0;
            try {
                valor = Double.parseDouble(tfValor.getText().replaceAll(",", "."));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "ERRO no valor!");
                return;
            }
            if(valor<=0){
                JOptionPane.showMessageDialog(rootPane, "O Valor deve ser Maior que 0!");
                tfValor.requestFocus();
                return ;
            }
            Date data = Util.verificaData(tfData.getText());
            if(data==null){
                JOptionPane.showMessageDialog(rootPane, "Data inválida!");
                return ;
            }
            
            itemContaBancaria.setBloqueada(cbBloqueado.isSelected());
            itemContaBancaria.setContaBancaria(contaBancaria);
            itemContaBancaria.setDescricao(tfDescricao.getText());
            if(rbEntrada.isSelected()){
                itemContaBancaria.setEntrada(valor);
                itemContaBancaria.setSaida(0);
            } else {
                itemContaBancaria.setEntrada(0);
                itemContaBancaria.setSaida(valor);
            }
            itemContaBancaria.setData(data);

            if (itemContaBancaria.getId() == null) {

                dao.add(itemContaBancaria);

            } else {
                dao.update(itemContaBancaria);

            }
            limpaCampos();
            dispose();
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void tfDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfDataFocusLost
        if(Util.verificaData(tfData.getText())==null){
            JOptionPane.showMessageDialog(rootPane, "Data inválida!");
            tfData.setText("");
        }
    }//GEN-LAST:event_tfDataFocusLost

    private void tfValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfValorFocusLost
        if(Util.verificaValor(tfValor.getText(), 0)==null){
            tfValor.setText("");
        }
    }//GEN-LAST:event_tfValorFocusLost

    private void limpaCampos() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMoviCadEditaContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMoviCadEditaContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMoviCadEditaContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMoviCadEditaContaBancaria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMoviCadEditaContaBancaria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cbBloqueado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JRadioButton rbEntrada;
    private javax.swing.JRadioButton rbSaida;
    private javax.swing.JTextField tfConta;
    private javax.swing.JFormattedTextField tfData;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JFormattedTextField tfValor;
    // End of variables declaration//GEN-END:variables
}
