/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.telas;

import br.usuario.Usuario;
import br.usuario.UsuarioDAO;
import br.util.Ativo;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Pedro Saraiva
 */
public class TelaPermissoes extends javax.swing.JDialog {

    private static Usuario usuario;

    public static Usuario chamaTela(Usuario usuario) {
        new TelaPermissoes(usuario).setVisible(true);
        return TelaPermissoes.usuario;
    }

    public TelaPermissoes() {
        initComponents();
        setModal(true);
        setLocationRelativeTo(this);
    }

    public TelaPermissoes(Usuario usuario) {
        initComponents();
        setModal(true);
        setLocationRelativeTo(this);
        this.usuario = usuario;
        lblUsuario.setText(usuario.getNome());
        verificaPermissoes();
    }

    public void verificaPermissoes() {
        if (usuario.getPermissao().size() > 0) {
            ArrayList<Component> listaComponentes = adicionaPaineis();
            for (Component componente : listaComponentes) {
                JCheckBox ck = null;
                try {
                    ck = (JCheckBox) componente;
                } catch (Exception ex) {

                }
                if (ck != null) {
                    ck.setSelected(usuario.getPermissao().contains(ck.getName()));                    
                }

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        CE_PRODUTO = new javax.swing.JCheckBox();
        EXCLUIR_PRODUTO = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        EXCLUIR_PRODUTO1 = new javax.swing.JCheckBox();
        EXCLUIR_PRODUTO2 = new javax.swing.JCheckBox();
        EXCLUIR_PRODUTO3 = new javax.swing.JCheckBox();
        EXCLUIR_PRODUTO4 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        CE_VENDEDOR = new javax.swing.JCheckBox();
        EXCLUIR_VENDEDOR = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        EXCLUIR_VENDEDOR1 = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        CE_EMPRESA = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE17 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        CE_CLIENTE = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE2 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE13 = new javax.swing.JCheckBox();
        jPanel9 = new javax.swing.JPanel();
        CE_GRUPO_PRODUTOS = new javax.swing.JCheckBox();
        EXCLUIR_GRUPO_PRODUTO = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel14 = new javax.swing.JPanel();
        CE_EMPRESA1 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jPanel15 = new javax.swing.JPanel();
        CE_EMPRESA2 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE19 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        CE_CLIENTE1 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE1 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE3 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE4 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE8 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE9 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE10 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE11 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE12 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE16 = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        jCheckBox8 = new javax.swing.JCheckBox();
        CE_CLIENTE5 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE14 = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        CE_CLIENTE3 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE5 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE6 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE7 = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        CE_CLIENTE4 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE15 = new javax.swing.JCheckBox();
        CE_CLIENTE6 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE18 = new javax.swing.JCheckBox();
        EXCLUIR_CLIENTE20 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        lbTexto = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto/Serviço"));

        CE_PRODUTO.setText("Cadastrar/Editar ");
        CE_PRODUTO.setName("CE_PRODUTO"); // NOI18N
        CE_PRODUTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_PRODUTOActionPerformed(evt);
            }
        });

        EXCLUIR_PRODUTO.setText("Excluir");
        EXCLUIR_PRODUTO.setName("EXCLUIR_PRODUTO"); // NOI18N

        jCheckBox6.setText("Visualizar");
        jCheckBox6.setName("V_PRODUTO"); // NOI18N

        EXCLUIR_PRODUTO1.setText("Relat. Curva ABC");
        EXCLUIR_PRODUTO1.setName("REL_CURVA_ABC"); // NOI18N

        EXCLUIR_PRODUTO2.setText("Relat. Estoque Minimo");
        EXCLUIR_PRODUTO2.setName("REL_EST_MIN"); // NOI18N

        EXCLUIR_PRODUTO3.setText("Relat. Histórico de Produto");
        EXCLUIR_PRODUTO3.setName("REL_HIST_PRODUTO"); // NOI18N

        EXCLUIR_PRODUTO4.setText("Relat. Relação de Produtos");
        EXCLUIR_PRODUTO4.setName("REL_RELA_PRODUTOS"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CE_PRODUTO)
                    .addComponent(EXCLUIR_PRODUTO)
                    .addComponent(jCheckBox6)
                    .addComponent(EXCLUIR_PRODUTO3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXCLUIR_PRODUTO1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXCLUIR_PRODUTO2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXCLUIR_PRODUTO4, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jCheckBox6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CE_PRODUTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXCLUIR_PRODUTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXCLUIR_PRODUTO1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EXCLUIR_PRODUTO2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXCLUIR_PRODUTO3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXCLUIR_PRODUTO4)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 190, 290));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendedor"));

        CE_VENDEDOR.setText("Cadastrar/Editar ");
        CE_VENDEDOR.setName("CE_VENDEDOR"); // NOI18N
        CE_VENDEDOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_VENDEDORActionPerformed(evt);
            }
        });

        EXCLUIR_VENDEDOR.setText("Excluir ");
        EXCLUIR_VENDEDOR.setName("EXCLUIR_VENDEDOR"); // NOI18N

        jCheckBox5.setText("Visualizar");
        jCheckBox5.setName("V_VENDEDOR"); // NOI18N

        EXCLUIR_VENDEDOR1.setText("Relatório de Comissão");
        EXCLUIR_VENDEDOR1.setName("REL_COMISSAO"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CE_VENDEDOR)
                    .addComponent(EXCLUIR_VENDEDOR)
                    .addComponent(jCheckBox5)
                    .addComponent(EXCLUIR_VENDEDOR1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jCheckBox5)
                .addGap(1, 1, 1)
                .addComponent(CE_VENDEDOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXCLUIR_VENDEDOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXCLUIR_VENDEDOR1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 160, 140));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Conta Bancária"));

        CE_EMPRESA.setText("Cadastrar/Editar ");
        CE_EMPRESA.setName("CE_CONTA_BANCARIA"); // NOI18N
        CE_EMPRESA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_EMPRESAActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Visualizar");
        jCheckBox4.setName("V_CONTA_BANCARIA"); // NOI18N

        EXCLUIR_CLIENTE17.setText("Excluir ");
        EXCLUIR_CLIENTE17.setName("EXCLUIR_CONTA_BANCARIA"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CE_EMPRESA)
                    .addComponent(jCheckBox4)
                    .addComponent(EXCLUIR_CLIENTE17))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jCheckBox4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CE_EMPRESA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EXCLUIR_CLIENTE17)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 160, 140));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        CE_CLIENTE.setText("Cadastrar/Editar ");
        CE_CLIENTE.setName("CE_CLIENTE"); // NOI18N
        CE_CLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_CLIENTEActionPerformed(evt);
            }
        });

        EXCLUIR_CLIENTE.setText("Excluir ");
        EXCLUIR_CLIENTE.setName("EXCLUIR_CLIENTE"); // NOI18N

        jCheckBox3.setText("Visualizar");
        jCheckBox3.setName("V_CLIENTE"); // NOI18N

        EXCLUIR_CLIENTE2.setText("Relat. Histórico Cliente");
        EXCLUIR_CLIENTE2.setName("RELA_HIST_CLIENTE"); // NOI18N

        EXCLUIR_CLIENTE13.setText("Relat. Curva ABC");
        EXCLUIR_CLIENTE13.setName("RELA_CURVA_ABC_CLIENTE"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CE_CLIENTE)
                    .addComponent(EXCLUIR_CLIENTE))
                .addGap(106, 106, 106))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox3)
                    .addComponent(EXCLUIR_CLIENTE2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EXCLUIR_CLIENTE13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CE_CLIENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EXCLUIR_CLIENTE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EXCLUIR_CLIENTE2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EXCLUIR_CLIENTE13))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 140));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Grupo de Produtos"));

        CE_GRUPO_PRODUTOS.setText("Cadastrar/Editar ");
        CE_GRUPO_PRODUTOS.setName("CE_GRUPO_PRODUTO"); // NOI18N
        CE_GRUPO_PRODUTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_GRUPO_PRODUTOSActionPerformed(evt);
            }
        });

        EXCLUIR_GRUPO_PRODUTO.setText("Excluir ");
        EXCLUIR_GRUPO_PRODUTO.setName("EXCLUIR_GRUPO_PRODUTO"); // NOI18N

        jCheckBox1.setText("Relat. de Produtos por Grupo");
        jCheckBox1.setName("REL_PRODU_GRUPO"); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Visualizar");
        jCheckBox2.setName("V_GRUPO_PRODUTO"); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CE_GRUPO_PRODUTOS)
                    .addComponent(EXCLUIR_GRUPO_PRODUTO)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2))
                .addGap(59, 59, 59))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CE_GRUPO_PRODUTOS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EXCLUIR_GRUPO_PRODUTO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 180, 140));

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Empresa"));

        CE_EMPRESA1.setText("Cadastrar/Editar ");
        CE_EMPRESA1.setName("CE_EMPRESA"); // NOI18N
        CE_EMPRESA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_EMPRESA1ActionPerformed(evt);
            }
        });

        jCheckBox11.setText("Visualizar");
        jCheckBox11.setName("V_EMPRESA"); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CE_EMPRESA1)
                    .addComponent(jCheckBox11))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jCheckBox11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CE_EMPRESA1)
                .addGap(0, 71, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 160, 140));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedor"));

        CE_EMPRESA2.setText("Cadastrar/Editar ");
        CE_EMPRESA2.setName("CE_FORNECEDOR"); // NOI18N
        CE_EMPRESA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_EMPRESA2ActionPerformed(evt);
            }
        });

        jCheckBox12.setText("Visualizar");
        jCheckBox12.setName("V_FORNECEDOR"); // NOI18N

        EXCLUIR_CLIENTE19.setText("Excluir ");
        EXCLUIR_CLIENTE19.setName("EXCLUIR_FORNECEDOR"); // NOI18N

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CE_EMPRESA2)
                    .addComponent(jCheckBox12)
                    .addComponent(EXCLUIR_CLIENTE19))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CE_EMPRESA2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EXCLUIR_CLIENTE19)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 160, 140));

        jTabbedPane1.addTab("Cadastros", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda"));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CE_CLIENTE1.setText("Realizar Venda à Vista");
        CE_CLIENTE1.setName("REALIZAR_VV"); // NOI18N
        CE_CLIENTE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_CLIENTE1ActionPerformed(evt);
            }
        });
        jPanel10.add(CE_CLIENTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        EXCLUIR_CLIENTE1.setText("Visualizar Todas as Vendas");
        EXCLUIR_CLIENTE1.setName("VISUAL_TODAS_VENDAS"); // NOI18N
        EXCLUIR_CLIENTE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_CLIENTE1ActionPerformed(evt);
            }
        });
        jPanel10.add(EXCLUIR_CLIENTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jCheckBox7.setText("Visualizar");
        jCheckBox7.setName("V_VENDA"); // NOI18N
        jPanel10.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        EXCLUIR_CLIENTE3.setText("Realizar Venda à Prazo");
        EXCLUIR_CLIENTE3.setName("REALIZAR_VP"); // NOI18N
        jPanel10.add(EXCLUIR_CLIENTE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        EXCLUIR_CLIENTE4.setText("Realizar Venda à Cartão");
        EXCLUIR_CLIENTE4.setName("REALIZAR_VC"); // NOI18N
        EXCLUIR_CLIENTE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_CLIENTE4ActionPerformed(evt);
            }
        });
        jPanel10.add(EXCLUIR_CLIENTE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        EXCLUIR_CLIENTE8.setText("Cancelar Item de Venda");
        EXCLUIR_CLIENTE8.setName("CANCEL_ITEM_VENDA"); // NOI18N
        jPanel10.add(EXCLUIR_CLIENTE8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        EXCLUIR_CLIENTE9.setText("Cancelar Venda");
        EXCLUIR_CLIENTE9.setName("CANCEL_VENDA"); // NOI18N
        jPanel10.add(EXCLUIR_CLIENTE9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        EXCLUIR_CLIENTE10.setText("Permitir que Clientes em atraso Comprem");
        EXCLUIR_CLIENTE10.setName("PERMITIR_QUE_CLIENTES_EM_ATRASO_COMPREM"); // NOI18N
        EXCLUIR_CLIENTE10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_CLIENTE10ActionPerformed(evt);
            }
        });
        jPanel10.add(EXCLUIR_CLIENTE10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        EXCLUIR_CLIENTE11.setText("Listar Vendas");
        EXCLUIR_CLIENTE11.setName("LISTAR_VENDAS"); // NOI18N
        EXCLUIR_CLIENTE11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_CLIENTE11ActionPerformed(evt);
            }
        });
        jPanel10.add(EXCLUIR_CLIENTE11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        EXCLUIR_CLIENTE12.setText("Permitir Alteração do Desconto");
        EXCLUIR_CLIENTE12.setName("PERMITIR_ALTERACAO_DESCONTO_VENDA"); // NOI18N
        EXCLUIR_CLIENTE12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_CLIENTE12ActionPerformed(evt);
            }
        });
        jPanel10.add(EXCLUIR_CLIENTE12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        EXCLUIR_CLIENTE16.setText("Inserir Orçamento");
        EXCLUIR_CLIENTE16.setName("INSERIR_ORCAMENTO"); // NOI18N
        EXCLUIR_CLIENTE16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_CLIENTE16ActionPerformed(evt);
            }
        });
        jPanel10.add(EXCLUIR_CLIENTE16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 240, 280));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Cartão Crédito/Débito"));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox8.setText("Visualizar");
        jCheckBox8.setName("V_CARTAO"); // NOI18N
        jPanel11.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        CE_CLIENTE5.setText("Adicionar Cartão");
        CE_CLIENTE5.setName("ADICIONA_CONTA_CARTAO"); // NOI18N
        CE_CLIENTE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_CLIENTE5ActionPerformed(evt);
            }
        });
        jPanel11.add(CE_CLIENTE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        EXCLUIR_CLIENTE14.setText("Excluir Cartão");
        EXCLUIR_CLIENTE14.setName("EXCLUIR_CARTAO"); // NOI18N
        EXCLUIR_CLIENTE14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXCLUIR_CLIENTE14ActionPerformed(evt);
            }
        });
        jPanel11.add(EXCLUIR_CLIENTE14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 230, 140));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Contas á Receber"));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CE_CLIENTE3.setText("Adicionar Conta");
        CE_CLIENTE3.setName("ADICIONA_CONTA_RECEBER"); // NOI18N
        CE_CLIENTE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_CLIENTE3ActionPerformed(evt);
            }
        });
        jPanel12.add(CE_CLIENTE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        EXCLUIR_CLIENTE5.setText("Receber Conta");
        EXCLUIR_CLIENTE5.setName("RECEBER_CONTA_RECEBER"); // NOI18N
        jPanel12.add(EXCLUIR_CLIENTE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jCheckBox9.setText("Visualizar");
        jCheckBox9.setName("V_CONTA_RECEBER"); // NOI18N
        jPanel12.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        EXCLUIR_CLIENTE6.setText("Editar Conta");
        EXCLUIR_CLIENTE6.setName("EDITAR_CONTA_RECEBER"); // NOI18N
        jPanel12.add(EXCLUIR_CLIENTE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        EXCLUIR_CLIENTE7.setText("Excluir Conta");
        EXCLUIR_CLIENTE7.setName("EXCLUIR_CONTA_RECEBER"); // NOI18N
        jPanel12.add(EXCLUIR_CLIENTE7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 230, 140));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Caixa"));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CE_CLIENTE4.setText("Fechar Caixa");
        CE_CLIENTE4.setName("FECHA_CAIXA"); // NOI18N
        CE_CLIENTE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_CLIENTE4ActionPerformed(evt);
            }
        });
        jPanel13.add(CE_CLIENTE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jCheckBox10.setText("Visualizar");
        jCheckBox10.setName("V_CAIXA"); // NOI18N
        jPanel13.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        EXCLUIR_CLIENTE15.setText("Excluir Caixa");
        EXCLUIR_CLIENTE15.setName("EXCLUIR_CAIXA"); // NOI18N
        jPanel13.add(EXCLUIR_CLIENTE15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        CE_CLIENTE6.setText("Abrir/Adicionar Caixa");
        CE_CLIENTE6.setName("ADICIONA_CAIXA"); // NOI18N
        CE_CLIENTE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CE_CLIENTE6ActionPerformed(evt);
            }
        });
        jPanel13.add(CE_CLIENTE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        EXCLUIR_CLIENTE18.setText("Imprimir Caixa");
        EXCLUIR_CLIENTE18.setName("IMPRIMIR_CAIXA"); // NOI18N
        jPanel13.add(EXCLUIR_CLIENTE18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        EXCLUIR_CLIENTE20.setText("Realizar Sangria");
        EXCLUIR_CLIENTE20.setName("REALIZAR_SANGRIA"); // NOI18N
        jPanel13.add(EXCLUIR_CLIENTE20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 280));

        jTabbedPane1.addTab("Movimentações", jPanel3);

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder("Geral"));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox13.setText("Contas à Pagar");
        jCheckBox13.setName("CONTAS_PAGAR"); // NOI18N
        jPanel16.add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jCheckBox14.setText("Caixa Geral");
        jCheckBox14.setName("CAIXA_GERAL"); // NOI18N
        jPanel16.add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jCheckBox15.setText("Listar Caixas");
        jCheckBox15.setName("LISTAR_CAIXAS"); // NOI18N
        jPanel16.add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(383, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Geral", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 720, 360));

        lbTexto.setFont(new java.awt.Font("Verdana", 1, 30)); // NOI18N
        lbTexto.setText("Permissões de Usuário");
        jPanel1.add(lbTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 630, 40));

        lblUsuario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblUsuario.setText("jLabel1");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/pataverde.png"))); // NOI18N
        btSalvar.setToolTipText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 43, -1));

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/imagens/close.png"))); // NOI18N
        btCancelar.setToolTipText("Sair");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, 43, 41));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CE_PRODUTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_PRODUTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_PRODUTOActionPerformed

    private void CE_VENDEDORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_VENDEDORActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_VENDEDORActionPerformed

    private void CE_EMPRESAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_EMPRESAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_EMPRESAActionPerformed

    private void CE_CLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_CLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_CLIENTEActionPerformed

    private void CE_GRUPO_PRODUTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_GRUPO_PRODUTOSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_GRUPO_PRODUTOSActionPerformed

    private List<Component> converteArrayListaComponentes(Component[] listaComp) {
        List<Component> lista = new ArrayList<>();
        for (Component c : listaComp) {
            lista.add(c);
        }
        return lista;
    }
    
    private ArrayList<Component> adicionaPaineis(){
        ArrayList<Component> listaComponentes = new ArrayList<>();
        listaComponentes.addAll(converteArrayListaComponentes(jPanel8.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel7.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel5.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel9.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel6.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel10.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel11.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel12.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel13.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel14.getComponents()));
        listaComponentes.addAll(converteArrayListaComponentes(jPanel15.getComponents()));        
        listaComponentes.addAll(converteArrayListaComponentes(jPanel16.getComponents()));        
        return listaComponentes;
    }
    
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        ArrayList<Component> listaComponentes = adicionaPaineis();
        usuario.setPermissao(new HashSet<String>());
        for (Component componente : listaComponentes) {
            JCheckBox ck = null;
            try {
                ck = (JCheckBox) componente;
            } catch (Exception ex) {

            }
            if (ck != null) {
                if (ck.isSelected()) {

                    usuario.getPermissao().add(ck.getName());
                }
            }

        }
        UsuarioDAO dao = new UsuarioDAO();
        dao.update(usuario);
        Ativo.setUsuario(usuario);
        dispose();
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btCancelarActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void CE_CLIENTE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_CLIENTE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_CLIENTE1ActionPerformed

    private void CE_CLIENTE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_CLIENTE3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_CLIENTE3ActionPerformed

    private void EXCLUIR_CLIENTE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_CLIENTE4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIR_CLIENTE4ActionPerformed

    private void EXCLUIR_CLIENTE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_CLIENTE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIR_CLIENTE1ActionPerformed

    private void EXCLUIR_CLIENTE10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_CLIENTE10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIR_CLIENTE10ActionPerformed

    private void EXCLUIR_CLIENTE11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_CLIENTE11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIR_CLIENTE11ActionPerformed

    private void EXCLUIR_CLIENTE12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_CLIENTE12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIR_CLIENTE12ActionPerformed

    private void CE_CLIENTE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_CLIENTE4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_CLIENTE4ActionPerformed

    private void CE_CLIENTE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_CLIENTE5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_CLIENTE5ActionPerformed

    private void EXCLUIR_CLIENTE14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_CLIENTE14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIR_CLIENTE14ActionPerformed

    private void EXCLUIR_CLIENTE16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXCLUIR_CLIENTE16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EXCLUIR_CLIENTE16ActionPerformed

    private void CE_CLIENTE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_CLIENTE6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_CLIENTE6ActionPerformed

    private void CE_EMPRESA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_EMPRESA1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_EMPRESA1ActionPerformed

    private void CE_EMPRESA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CE_EMPRESA2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CE_EMPRESA2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPermissoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPermissoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CE_CLIENTE;
    private javax.swing.JCheckBox CE_CLIENTE1;
    private javax.swing.JCheckBox CE_CLIENTE3;
    private javax.swing.JCheckBox CE_CLIENTE4;
    private javax.swing.JCheckBox CE_CLIENTE5;
    private javax.swing.JCheckBox CE_CLIENTE6;
    private javax.swing.JCheckBox CE_EMPRESA;
    private javax.swing.JCheckBox CE_EMPRESA1;
    private javax.swing.JCheckBox CE_EMPRESA2;
    private javax.swing.JCheckBox CE_GRUPO_PRODUTOS;
    private javax.swing.JCheckBox CE_PRODUTO;
    private javax.swing.JCheckBox CE_VENDEDOR;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE1;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE10;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE11;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE12;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE13;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE14;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE15;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE16;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE17;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE18;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE19;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE2;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE20;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE3;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE4;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE5;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE6;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE7;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE8;
    private javax.swing.JCheckBox EXCLUIR_CLIENTE9;
    private javax.swing.JCheckBox EXCLUIR_GRUPO_PRODUTO;
    private javax.swing.JCheckBox EXCLUIR_PRODUTO;
    private javax.swing.JCheckBox EXCLUIR_PRODUTO1;
    private javax.swing.JCheckBox EXCLUIR_PRODUTO2;
    private javax.swing.JCheckBox EXCLUIR_PRODUTO3;
    private javax.swing.JCheckBox EXCLUIR_PRODUTO4;
    private javax.swing.JCheckBox EXCLUIR_VENDEDOR;
    private javax.swing.JCheckBox EXCLUIR_VENDEDOR1;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbTexto;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
